import {abilityStats} from '../config/abilityConfig.js';
export const LANGUAGES={en:'English (US)',es:'Español',pt:'Português (Brasil)'};
const en={
  menu:'Main menu',character:'Character',stage:'Stage',steps:'Steps',prepare:'PREPARE YOUR JOURNEY',chooseCharacter:'Choose your character',chooseMap:'Choose your stage',continue:'Continue',play:'Ride into the fray',life:'HEALTH',damage:'DAMAGE',duration:'DURATION',minutes:'minutes',coins:'coins',market:"Bento's Market",permanentUpgrades:'Permanent upgrades',permanentHelp:'Market upgrades stay with you in every run.',controlsHelp:'WASD / arrows or touch control. Automatic attacks.',
  'hero.joao':'Weathered leather, trusty whip and nerves of steel.','hero.maria':'A lightning quick gunslinger with a faithful revolver.','hero.indigo':'A skilled desert archer whose arrows pierce the darkness.',
  'map.desert':'Desert of the Forgotten','map.mine':'Nightfall Mine','map.town':'Ghost Town',
  'mapDesc.desert':'Open dunes, cacti and vultures under a relentless sun.','mapDesc.mine':'Dark galleries, ore carts and glowing lantern posts.','mapDesc.town':'An abandoned western town full of boarded shops and restless dead.',
  est:'EST. 1887 / LAWLESS LANDS',chapter:'CHAPTER ONE',tag:'ONE LAST CHANCE UNDER THE SUN',tagline:'The desert does not bury its dead.<br>It brings them back.',newGame:'New game',settings:'Settings',exit:'Exit',survive:'SURVIVE UNTIL THE LAST SUNSET',footer:'A SURVIVOR IN THE OLD WEST',version:'TWO CURSED BOSSES / 0.6',settingsTitle:'Settings',settingsIntro:'TUNE YOUR JOURNEY',wind:'Menu wind',sound:'Game sounds',music:'Western music',motion:'The menu respects reduced motion settings.',back:'Back',backMenu:'Back to menu',testAudio:'Test audio / retry',audioHelp:'Audio starts after a click, tap or keypress. Check your device volume.',goodbye:'UNTIL NEXT TIME, STRANGER',farewell:'The desert awaits.',closeTab:'You may close this tab or go back to the menu.',saved:'Preference saved.',saveFailed:'Applied for this session; saving is unavailable.',language:'Language',
  countdown:'TIME LEFT',pause:'Pause game',resume:'Continue',quitRun:'End run',level:'LEVEL',runCoins:'Run',warningVultures:'⚠ Vultures incoming! Dodge the marked path!',merchantHint:'Bento {arrow} · {distance} m · leaves in {time}s · come closer to trade',bossFire:'CURSED GRAVEDIGGER · FIRE RING',bossMarshal:'SHADOW MARSHAL · FIRE RING',bossLife:'{hp} / {max} HP · Stay away from the flames',mission:'SIDE QUEST',missionBat:'Defeat bats',missionCrate:'Break crates',missionSkeleton:'Defeat skeleton gunfighters',missionTime:'{time}s remaining',missionFailed:'Side quest failed',stormWarning:'DUST STORM · AVOID THE TORNADOES!',
  perkAlert:'LEVEL {level} · YOUR LEGEND GROWS',pauseTitle:'Take a breath, outlaw',paused:'RUN PAUSED',resumeButton:'Continue',endButton:'End and return',winIntro:'THE SUN RISES FOR THE STRONG',loseIntro:'THE DUST COVERS ANOTHER TALE',winTitle:'You survived!',loseTitle:'End of the trail',retry:'Play again',backSelect:'Return to selection',statSummary:'{kills} enemies · Level {level}',coinsSaved:'{coins} coins banked',coinsSession:'Balance available only this session.',
  missionSuccess:'QUEST COMPLETE',chooseReward:'Pick your reward',missionCard:'Upgrade a card',missionCoins:'+25 run coins',missionHealth:'+20 max HP and heal 40',chooseCard:'Upgrade this card',
  shopTitle:'BENTO’S MARKET',savedCoins:'◈ {coins} saved',merchantName:'BENTO, THE WANDERER',merchantTitle:'Prepare for<br>your next journey.',merchantSays:'“What you buy here stays with you.”',merchantThanks:'“A fine deal, traveler.” This upgrade lasts for this run.',merchantThanksForever:'“Thank you, traveler. This upgrade is yours for good.”',shopPermanent:'PERMANENT UPGRADES',shopFoot:'Uses only saved coins. Each product costs more after each purchase.',buy:'Buy · ◈ {price}',limit:'Limit reached',permanent:'PERMANENT · RANK {rank}',runShopIntro:'BENTO IN THE WILDS · RUN PAUSED',runShopTitle:'Supplies for the road',runMoney:'◈ {coins} coins from this run · separate from your saved balance.',runShopHelp:'These purchases last for this run only. Only cards you own are listed.',runRank:'THIS RUN · {type} {rank}',runLevel:'RANK',runUpgrade:'UPGRADES',leaveMerchant:'Back to the fight →',haste:'Quick Trigger',spur:'Wanderer’s Spurs',primaryShop:'Primary Weapon',primaryDesc:'+3 damage. Next damage: {damage}.',hasteDesc:'+6% attack speed this run.',spurDesc:'+5% move speed this run.',
  cardHeading:'Write your fate.',cardPending:'LEVEL {level} · {choices} CHOICE(S) LEFT',cardPrompt:'Choose one card. The run pauses while you decide.',unlock:'UNLOCK',evolve:'UPGRADE',grade:'RANK',combo:'CHAIN',comboStart:'Starts a new chain.',comboHealth:'Heal {heal} extra HP.',comboDamage:'+{damage}% damage for 20 s.',deckRule:'THE OUTLAW DECK · Change cards to build a chain up to three. Repeating strengthens a card and restarts the chain.',
  'ability.pistol':'Frontier Revolver','ability.molotov':'Molotov Cocktail','ability.heart':'Cowboy Heart','ability.horseshoe':'Cursed Horseshoes','ability.ghostShot':'Ghost Bullet','ability.requiem':'Dust Requiem','ability.silverRain':'Silver Rain','ability.lantern':'Cursed Lantern','ability.soulHarvest':'Soul Harvest','ability.boneStorm':'Bone Storm','ability.ironWill':'Iron Will','ability.lastStand':'Last Shot',
  'shop.health':'Cowboy Heart','shop.attack':'Quick Hands','shop.movement':'Desert Stride','shop.primary':'Leather and Steel','shop.armor':'Reinforced Leather','shop.magnet':'Prospector’s Magnet',
  'shopDesc.health':'+20 starting HP per purchase.','shopDesc.attack':'+8% attack speed per purchase (all weapons).','shopDesc.movement':'+5% movement speed per purchase.','shopDesc.primary':'+2 base damage for your hero’s primary weapon.','shopDesc.armor':'+2 starting armor per purchase.','shopDesc.magnet':'+0.7 pickup radius per purchase.',
  healthDesc:'+20 max HP and heal 20 for this run.',pistolDesc:'{damage} damage · one shot every {cooldown}s.',molotovDesc:'{damage} damage/s · fire for {duration}s · throw every {cooldown}s.',horseshoeDesc:'{count} orbiting horseshoes · {damage} contact damage.',ghostShotDesc:'{damage} damage · pierces {pierce} enemies · every {cooldown}s.',requiemDesc:'Dust wave {radius} m · {damage} damage and knockback · every {cooldown}s.',silverRainDesc:'{count} radial bullets · {damage} damage each · every {cooldown}s.',lanternDesc:'Cursed glow burns nearby enemies: {damage} damage/s in {radius} m.',soulHarvestDesc:'Heal {heal} HP per kill (up to maximum).',boneStormDesc:'{count} bone shards · {damage} damage · every {cooldown}s.',ironWillDesc:'+3 armor this run · {armor} armor from this card in total.',lastStandDesc:'Below 35% HP: +{attack}% attack speed.',
};
const es={
  menu:'Menú principal',character:'Personaje',stage:'Escenario',steps:'Pasos',prepare:'PREPARA TU VIAJE',chooseCharacter:'Elige tu personaje',chooseMap:'Elige tu escenario',continue:'Continuar',play:'Comenzar partida',life:'VIDA',damage:'DAÑO',duration:'DURACIÓN',minutes:'minutos',coins:'monedas',market:'Mercado de Bento',permanentUpgrades:'Mejoras permanentes',permanentHelp:'Las mejoras del mercado duran todas las partidas.',controlsHelp:'WASD / flechas o control táctil. Ataques automáticos.',
  'hero.joao':'Cuero gastado, látigo fiel y nervios de acero.','hero.maria':'Pistolera veloz con un revólver de confianza.','hero.indigo':'Arquero del desierto cuyas flechas atraviesan la oscuridad.',
  'map.desert':'Desierto de los Olvidados','map.mine':'Mina de la Noche','map.town':'Pueblo Fantasma','mapDesc.desert':'Dunas, cactus y buitres bajo un sol implacable.','mapDesc.mine':'Galerías oscuras, vagonetas y postes iluminados.','mapDesc.town':'Pueblo del viejo oeste con tiendas tapiadas y muertos inquietos.',
  est:'EST. 1887 / TIERRAS SIN LEY',chapter:'CAPÍTULO UNO',tag:'UNA ÚLTIMA OPORTUNIDAD BAJO EL SOL',tagline:'El desierto no entierra a sus muertos.<br>Los devuelve.',newGame:'Nueva partida',settings:'Configuración',exit:'Salir',survive:'SOBREVIVE HASTA EL ÚLTIMO ATARDECER',footer:'UN SURVIVOR EN EL VIEJO OESTE',version:'DOS JEFES MALDITOS / 0.6',settingsTitle:'Configuración',settingsIntro:'AJUSTA TU VIAJE',wind:'Viento del menú',sound:'Sonidos del juego',music:'Música del oeste',motion:'El menú respeta la preferencia de movimiento reducido.',back:'Volver',backMenu:'Volver al menú',testAudio:'Probar audio / reintentar',audioHelp:'El audio comienza tras un clic, toque o tecla. Comprueba el volumen.',goodbye:'HASTA LA PRÓXIMA, FORASTERO',farewell:'El desierto espera.',closeTab:'Puedes cerrar la pestaña o volver al menú.',saved:'Preferencia guardada.',saveFailed:'Aplicado en esta sesión; no se pudo guardar.',language:'Idioma',
  countdown:'TIEMPO RESTANTE',pause:'Pausar partida',resume:'Continuar',quitRun:'Terminar partida',level:'NIVEL',runCoins:'Partida',warningVultures:'⚠ ¡Buitres a la vista! ¡Esquiva el camino marcado!',merchantHint:'Bento {arrow} · {distance} m · se va en {time}s · acércate para comerciar',bossFire:'SEPULTURERO MALDITO · CÍRCULO DE FUEGO',bossMarshal:'ALGUACIL DE LAS SOMBRAS · CÍRCULO DE FUEGO',bossLife:'{hp} / {max} VIDA · No toques las llamas',mission:'MISIÓN SECUNDARIA',missionBat:'Elimina murciélagos',missionCrate:'Rompe cajas',missionSkeleton:'Elimina pistoleros esqueleto',missionTime:'quedan {time}s',missionFailed:'Misión fallida',stormWarning:'TORMENTA DE POLVO · ¡ESQUIVA LOS TORNADOS!',perkAlert:'NIVEL {level} · CRECE TU LEYENDA',pauseTitle:'Respira, forastero',paused:'PARTIDA PAUSADA',resumeButton:'Continuar',endButton:'Terminar y volver',winIntro:'EL SOL SALE PARA LOS FUERTES',loseIntro:'EL POLVO CUBRE OTRA HISTORIA',winTitle:'¡Sobreviviste!',loseTitle:'Fin del camino',retry:'Jugar de nuevo',backSelect:'Volver a la selección',statSummary:'{kills} enemigos · Nivel {level}',coinsSaved:'{coins} monedas guardadas',coinsSession:'Saldo disponible solo en esta sesión.',
  missionSuccess:'MISIÓN CUMPLIDA',chooseReward:'Elige tu recompensa',missionCard:'Mejorar una carta',missionCoins:'+25 monedas de partida',missionHealth:'+20 vida máxima y recuperar 40',chooseCard:'Mejorar esta carta',
  shopTitle:'MERCADO DE BENTO',savedCoins:'◈ {coins} guardadas',merchantName:'BENTO, EL ANDARIEGO',merchantTitle:'Prepárate para<br>el próximo viaje.',merchantSays:'«Lo que compras aquí te acompaña».',merchantThanks:'«Buen trato, viajero». Esta mejora dura esta partida.',merchantThanksForever:'«Gracias, viajero». Esta mejora es tuya para siempre.',shopPermanent:'MEJORAS PERMANENTES',shopFoot:'Usa solo monedas guardadas. Los precios suben con cada compra.',buy:'Comprar · ◈ {price}',limit:'Límite alcanzado',permanent:'PERMANENTE · NIVEL {rank}',runShopIntro:'BENTO EN EL PÁRAMO · PARTIDA PAUSADA',runShopTitle:'Suministros para el camino',runMoney:'◈ {coins} monedas de esta partida · saldo separado del menú.',runShopHelp:'Las compras duran solo esta partida. Aparecen solo las cartas adquiridas.',runRank:'ESTA PARTIDA · {type} {rank}',runLevel:'NIVEL',runUpgrade:'MEJORAS',leaveMerchant:'Volver a la partida →',haste:'Gatillo Veloz',spur:'Espuelas del Andariego',primaryShop:'Arma principal',primaryDesc:'+3 de daño. Próximo daño: {damage}.',hasteDesc:'+6% de velocidad de ataque esta partida.',spurDesc:'+5% de movimiento esta partida.',
  cardHeading:'Escribe tu destino.',cardPending:'NIVEL {level} · {choices} ELECCIÓN(ES) PENDIENTE(S)',cardPrompt:'Elige una carta. La partida se detiene mientras decides.',unlock:'DESBLOQUEAR',evolve:'MEJORAR',grade:'GRADO',combo:'RACHA',comboStart:'Inicia una nueva racha.',comboHealth:'Cura {heal} de vida extra.',comboDamage:'+{damage}% de daño durante 20 s.',deckRule:'BARAJA DEL DESIERTO · Alternar cartas aumenta la racha hasta tres. Repetir mejora la carta y reinicia la racha.',
  'ability.pistol':'Pistola del Desierto','ability.molotov':'Cóctel Molotov','ability.heart':'Corazón de Vaquero','ability.horseshoe':'Herraduras Malditas','ability.ghostShot':'Bala Fantasma','ability.requiem':'Réquiem de Polvo','ability.silverRain':'Lluvia de Plata','ability.lantern':'Farol Maldito','ability.soulHarvest':'Cosecha de Almas','ability.boneStorm':'Tormenta de Huesos','ability.ironWill':'Voluntad de Hierro','ability.lastStand':'Último Disparo',
  'shop.health':'Corazón de Vaquero','shop.attack':'Manos Rápidas','shop.movement':'Paso del Desierto','shop.primary':'Cuero y Acero','shop.armor':'Cuero Reforzado','shop.magnet':'Imán del Minero',
  'shopDesc.health':'+20 de vida inicial por compra.','shopDesc.attack':'+8% de velocidad de ataque por compra.','shopDesc.movement':'+5% de movimiento por compra.','shopDesc.primary':'+2 de daño base al arma principal.','shopDesc.armor':'+2 de armadura inicial por compra.','shopDesc.magnet':'+0,7 al radio de recolección por compra.',
  healthDesc:'+20 de vida máxima y recupera 20.',pistolDesc:'{damage} de daño · disparo cada {cooldown}s.',molotovDesc:'{damage} de daño/s · fuego por {duration}s · lanzamiento cada {cooldown}s.',horseshoeDesc:'{count} herraduras giratorias · {damage} de daño por contacto.',ghostShotDesc:'{damage} de daño · atraviesa {pierce} enemigos · cada {cooldown}s.',requiemDesc:'Onda de polvo de {radius} m · {damage} de daño y empuje · cada {cooldown}s.',silverRainDesc:'{count} balas radiales · {damage} de daño · cada {cooldown}s.',lanternDesc:'La luz maldita quema enemigos: {damage} de daño/s en {radius} m.',soulHarvestDesc:'Recupera {heal} de vida por baja (hasta el máximo).',boneStormDesc:'{count} huesos · {damage} de daño · cada {cooldown}s.',ironWillDesc:'+3 de armadura esta partida · {armor} de la carta en total.',lastStandDesc:'Con menos de 35% de vida: +{attack}% de velocidad de ataque.',
};
const pt={
  menu:'Menu principal',character:'Personagem',stage:'Fase',steps:'Etapas',prepare:'PREPARE SUA JORNADA',chooseCharacter:'Escolha seu personagem',chooseMap:'Escolha sua fase',continue:'Continuar',play:'Jogar',life:'VIDA',damage:'DANO',duration:'DURAÇÃO',minutes:'minutos',coins:'moedas',market:'Mercado do Bento',permanentUpgrades:'Melhorias permanentes',permanentHelp:'As melhorias do mercado acompanham você em todas as partidas.',controlsHelp:'WASD / setas ou controle por toque. Ataques automáticos.',
  'hero.joao':'Couro gasto, chicote fiel e coragem de sobra.','hero.maria':'Pistoleira veloz com seu revólver de confiança.','hero.indigo':'Arqueiro do deserto cujas flechas atravessam a escuridão.',
  'map.desert':'Deserto dos Esquecidos','map.mine':'Mina da Noite','map.town':'Cidade Fantasma','mapDesc.desert':'Dunas, cactos e urubus sob um sol implacável.','mapDesc.mine':'Galerias escuras, vagonetes e postes com lampiões.','mapDesc.town':'Cidade abandonada de velho oeste, lojas fechadas e mortos inquietos.',
  est:'EST. 1887 / TERRAS SEM LEI',chapter:'CAPÍTULO UM',tag:'UM SOL IMPLACÁVEL. UMA ÚLTIMA CHANCE.',tagline:'O deserto não enterra seus mortos.<br>Ele os devolve.',newGame:'Novo jogo',settings:'Configurações',exit:'Sair',survive:'SOBREVIVA ATÉ O ÚLTIMO PÔR DO SOL',footer:'UM SURVIVOR NO VELHO OESTE',version:'DOIS CHEFES MALDITOS / 0.6',settingsTitle:'Configurações',settingsIntro:'AJUSTE SUA JORNADA',wind:'Vento do menu',sound:'Sons do jogo',music:'Música de faroeste',motion:'O cenário respeita a preferência de movimento reduzido.',back:'Voltar',backMenu:'Voltar ao menu',testAudio:'Testar áudio / tentar novamente',audioHelp:'O som começa após clique, toque ou tecla. Verifique o volume.',goodbye:'ATÉ A PRÓXIMA, FORASTEIRO',farewell:'O deserto espera.',closeTab:'Você pode fechar esta aba ou voltar ao menu.',saved:'Preferência salva.',saveFailed:'Aplicado nesta sessão; salvamento indisponível.',language:'Idioma',
  countdown:'TEMPO RESTANTE',pause:'Pausar partida',resume:'Continuar',quitRun:'Encerrar partida',level:'NÍVEL',runCoins:'Partida',warningVultures:'⚠ Bando de urubus! Saia da rota marcada!',merchantHint:'Bento {arrow} · {distance} m · parte em {time}s · aproxime-se para negociar',bossFire:'COVEIRO MALDITO · ARENA EM CHAMAS',bossMarshal:'XERIFE DAS SOMBRAS · ARENA EM CHAMAS',bossLife:'{hp} / {max} VIDA · Não toque nas chamas',mission:'MISSÃO SECUNDÁRIA',missionBat:'Mate morcegos',missionCrate:'Quebre caixas',missionSkeleton:'Mate esqueletos pistoleiros',missionTime:'restam {time}s',missionFailed:'Missão secundária falhou',stormWarning:'TEMPESTADE DE AREIA · DESVIE DOS TORNADOS!',perkAlert:'NÍVEL {level} · A LENDA CRESCE',pauseTitle:'Respire, forasteiro',paused:'PARTIDA PAUSADA',resumeButton:'Continuar',endButton:'Encerrar e voltar',winIntro:'O SOL NASCE PARA OS FORTES',loseIntro:'A POEIRA COBRE MAIS UMA HISTÓRIA',winTitle:'Você sobreviveu!',loseTitle:'Fim da jornada',retry:'Jogar novamente',backSelect:'Voltar à seleção',statSummary:'{kills} inimigos · Nível {level}',coinsSaved:'{coins} moedas guardadas',coinsSession:'Saldo disponível apenas nesta sessão.',
  missionSuccess:'MISSÃO CUMPRIDA',chooseReward:'Escolha sua recompensa',missionCard:'Evoluir uma carta',missionCoins:'+25 moedas da partida',missionHealth:'+20 de vida máxima e cura 40',chooseCard:'Evoluir esta carta',
  shopTitle:'MERCADO DO BENTO',savedCoins:'◈ {coins} guardadas',merchantName:'BENTO, O ANDARILHO',merchantTitle:'Prepare-se para<br>a próxima jornada.',merchantSays:'“O que você compra aqui fica com você.”',merchantThanks:'“Bom negócio, viajante.” Melhoria aplicada somente nesta partida.',merchantThanksForever:'“Obrigado, viajante.” Esta melhoria fica com você.',shopPermanent:'MELHORIAS PERMANENTES',shopFoot:'Usa apenas moedas guardadas. Cada produto fica mais caro a cada compra.',buy:'Comprar · ◈ {price}',limit:'Limite atingido',permanent:'PERMANENTE · NÍVEL {rank}',runShopIntro:'BENTO NO DESERTO · PARTIDA PAUSADA',runShopTitle:'Um reforço para a jornada',runMoney:'◈ {coins} moedas desta partida · saldo separado do menu.',runShopHelp:'As compras duram somente esta partida. Apenas habilidades adquiridas aparecem.',runRank:'SÓ NESTA PARTIDA · {type} {rank}',runLevel:'NÍVEL',runUpgrade:'MELHORIAS',leaveMerchant:'Voltar à partida →',haste:'Tambor Acelerado',spur:'Esporas do Andarilho',primaryShop:'Arma principal',primaryDesc:'+3 de dano. Próximo dano: {damage}.',hasteDesc:'+6% de velocidade de ataque nesta partida.',spurDesc:'+5% de movimento nesta partida.',
  cardHeading:'Escreva seu destino.',cardPending:'NÍVEL {level} · {choices} ESCOLHA(S) PENDENTE(S)',cardPrompt:'Escolha uma carta. A partida fica parada enquanto decide.',unlock:'DESBLOQUEAR',evolve:'EVOLUIR',grade:'GRAU',combo:'SEQUÊNCIA',comboStart:'Inicia uma nova sequência.',comboHealth:'Cura extra de {heal} de vida.',comboDamage:'+{damage}% de dano por 20 s.',deckRule:'TRINCA DO SERTÃO · Alternar cartas aumenta a sequência até 3. Repetir melhora a carta e reinicia a sequência.',
  'ability.pistol':'Pistola do Sertão','ability.molotov':'Coquetel Molotov','ability.heart':'Coração de Vaqueiro','ability.horseshoe':'Ferraduras Malditas','ability.ghostShot':'Bala Fantasma','ability.requiem':'Réquiem da Poeira','ability.silverRain':'Chuva de Prata','ability.lantern':'Lampião Maldito','ability.soulHarvest':'Colheita de Almas','ability.boneStorm':'Estilhaços de Ossos','ability.ironWill':'Vontade de Ferro','ability.lastStand':'Último Disparo',
  'shop.health':'Coração de Vaqueiro','shop.attack':'Mãos Ligeiras','shop.movement':'Passo do Sertão','shop.primary':'Couro e Aço','shop.armor':'Couro Reforçado','shop.magnet':'Ímã do Garimpo',
  'shopDesc.health':'+20 de vida inicial por compra.','shopDesc.attack':'+8% de velocidade de ataque por compra.','shopDesc.movement':'+5% de movimento por compra.','shopDesc.primary':'+2 de dano base à arma principal.','shopDesc.armor':'+2 de armadura inicial por compra.','shopDesc.magnet':'+0,7 de raio de atração por compra.',
  healthDesc:'+20 de vida máxima e recupera 20 nesta partida.',pistolDesc:'{damage} de dano · tiro a cada {cooldown}s.',molotovDesc:'{damage} de dano/s · fogo por {duration}s · arremesso a cada {cooldown}s.',horseshoeDesc:'{count} ferraduras giratórias · {damage} de dano por contato.',ghostShotDesc:'{damage} de dano · atravessa {pierce} inimigos · a cada {cooldown}s.',requiemDesc:'Onda de poeira de {radius} m · {damage} de dano e empurrão · a cada {cooldown}s.',silverRainDesc:'{count} balas em círculo · {damage} de dano · a cada {cooldown}s.',lanternDesc:'A luz profana queima inimigos: {damage} de dano/s em {radius} m.',soulHarvestDesc:'Recupera {heal} de vida ao abater um inimigo.',boneStormDesc:'{count} estilhaços · {damage} de dano · a cada {cooldown}s.',ironWillDesc:'+3 de armadura nesta partida · {armor} da carta no total.',lastStandDesc:'Abaixo de 35% da vida: +{attack}% de velocidade de ataque.',
};
const dictionary={en,es,pt};
Object.assign(en,{tutorialTitle:'How to play',tutorialMove:'Use WASD or arrow keys. On a touchscreen, touch and drag anywhere in the play area; the joystick appears under your finger. Your hero walks forward automatically.',tutorialAttack:'Attacks fire automatically. Collect XP to choose one of three cards.',tutorialLoot:'Walk through crates to find bandages or coins. Nearby loot is attracted to you.',tutorialShop:'Bento sells permanent upgrades on the menu and temporary cards during a run. Press Esc to pause.',abilitiesTitle:'Abilities',missionCrate:'Find crates'});
Object.assign(es,{tutorialTitle:'Cómo jugar',tutorialMove:'Usa WASD o las flechas. En pantallas táctiles, toca y arrastra en cualquier parte del mapa; el control aparece bajo el dedo. El personaje avanza solo.',tutorialAttack:'Los ataques son automáticos. Recoge XP y elige una de las tres cartas.',tutorialLoot:'Pasa por las cajas para encontrar vendas o monedas. Los objetos cercanos se acercan solos.',tutorialShop:'Bento vende mejoras permanentes en el menú y temporales en partida. Esc pausa.',abilitiesTitle:'Habilidades',missionCrate:'Encuentra cajas'});
Object.assign(pt,{tutorialTitle:'Como jogar',tutorialMove:'Use WASD ou as setas. No celular, toque e arraste em qualquer área da partida; o controle aparece sob o dedo. O personagem avança sozinho.',tutorialAttack:'Os ataques são automáticos. Colete XP e escolha uma entre três cartas.',tutorialLoot:'Passe por cima das caixas para achar bandagens ou moedas. Itens próximos são atraídos.',tutorialShop:'Bento vende melhorias permanentes no menu e temporárias na partida. Esc pausa.',abilitiesTitle:'Habilidades',missionCrate:'Encontre caixas'});
Object.assign(en,{tutorialCards:'Alternate cards on level up to build a short damage combo; repeat a card to reset the combo.'});
Object.assign(es,{tutorialCards:'Alterna cartas al subir de nivel para aumentar el combo de daño; repetir una carta reinicia el combo.'});
Object.assign(pt,{tutorialCards:'Alterne cartas ao evoluir para acumular um bônus temporário de dano; repetir a carta reinicia a sequência.'});
Object.assign(en,{cardHeading:'Choose a card',runShopTitle:"Bento's shop",runMoney:'◈ {coins} coins'});
Object.assign(es,{cardHeading:'Elige una carta',runShopTitle:'Tienda de Bento',runMoney:'◈ {coins} monedas'});
Object.assign(pt,{cardHeading:'Escolha uma carta',runShopTitle:'Loja do Bento',runMoney:'◈ {coins} moedas'});
Object.assign(en,{'shop.fortune':'Prospector’s Fortune','shop.learning':'Legend’s Apprentice','shopDesc.fortune':'+4 percentage points to crate bandage chance per purchase.','shopDesc.learning':'+5% experience gained per purchase.'});
Object.assign(es,{'shop.fortune':'Suerte del Minero','shop.learning':'Aprendiz de Leyenda','shopDesc.fortune':'+4 puntos de probabilidad de vendas en cajas por compra.','shopDesc.learning':'+5% de experiencia obtenida por compra.'});
Object.assign(pt,{'shop.fortune':'Sorte de Garimpeiro','shop.learning':'Lenda Aprendiz','shopDesc.fortune':'+4 pontos na chance de bandagem por caixa a cada compra.','shopDesc.learning':'+5% de experiência recebida por compra.'});
Object.assign(en,{
  version:'STORY CAMPAIGN / 0.7',storyMode:'Story mode',freeMode:'Free survival',arsenal:'Deck Arsenal',bestiary:'Bestiary',
  deckCount:'{count}/{max} cards equipped',deckHint:'Select at least {min}; only equipped cards appear during a run.',equip:'Equip',equipped:'Equipped',forge:'Combine cards',combine:'Combine',forged:'Created',equipIngredients:'Equip both ingredients',clearStage:'Clear {stage} in Story mode',
  unknownCreature:'Unknown',discoverCreature:'Defeat this enemy to reveal its entry.',bestiaryCount:'{count}/{total} entries discovered',creatures:'Creatures',bosses:'Bosses',weakness:'Weakness',counter:'Counter hero',speed:'SPEED',armor:'ARMOR',storyGoals:'Quests + bosses',storyProgress:'Quests {missions}/3 · Bosses {bosses}/3',storyClear:'Story cleared! Next stage and a hero unlocked.',storyIncomplete:'Story incomplete: {missions}/{total} quests, {bosses}/{all} bosses. Survive and meet all goals to unlock the next stage.',
  'hero.labuta':'Heavy Civil War veteran with a three-pellet shotgun. Tough but slow.', 'hero.rosa':'Railway scout with twin revolvers and quick feet.', 'hero.elias':'Mine veteran with a long-range piercing rifle and armor.', 'hero.silas':'Fast bounty hunter who throws paired knives.',
  'weapon.whip':'Whip','weapon.revolver':'Revolver','weapon.bow':'Bow','weapon.shotgun':'3-pellet shotgun','weapon.dual':'Twin revolvers','weapon.rifle':'Piercing rifle','weapon.knives':'Throwing knives',
  'missionDog':'Defeat chupacabras','missionMiner':'Defeat mine wraiths',
  'ability.bulwark':'Iron Bulwark','ability.inferno':'Unholy Fire','ability.silverStorm':'Silver Tempest',
  bulwarkDesc:'+2 armor and +10 maximum HP per card rank.',infernoDesc:'Fire and lantern deal +{damage} damage/s; their range grows.',silverStormDesc:'Silver rain gains {count} shots and +{damage} damage.',
  'enemy.bat':'Night bat','enemy.dog':'Chupacabra','enemy.vulture':'Carrion vulture','enemy.skeleton':'Skeleton gunfighter','enemy.miner':'Mine specter',
  'weakness.bat':'Wide attacks','weakness.dog':'Knockback','weakness.vulture':'Dodge the marked lanes','weakness.skeleton':'Piercing arrows','weakness.miner':'Fire',
  'boss.duneRider':'Dune Rider','boss.gravedigger':'Cursed Gravedigger','boss.shadowMarshal':'Shadow Marshal','boss.oreWraith':'Ore Wraith','boss.mineForeman':'Mine Foreman','boss.hollowEngine':'Hollow Engine','boss.bellRinger':'Bell Ringer','boss.ghostSheriff':'Ghost Sheriff','boss.widowOfDust':'Widow of Dust',
  'lore.bat':'Small swarms; a wide arc clears them.', 'lore.dog':'Hunts close to the ground and closes gaps quickly.', 'lore.vulture':'Charges along the lane marked when it appears.', 'lore.skeleton':'Fires from afar; close the distance sideways.', 'lore.miner':'Rises from dark galleries; fire breaks its advance.',
  'lore.duneRider':'A rider lost beneath the dunes; fires into open lanes.', 'lore.gravedigger':'Keeps the ring of fire tight. Burn through his armor.', 'lore.shadowMarshal':'Commands the sand with brutal charges.', 'lore.oreWraith':'Haunts the mine and fears the cursed lantern.', 'lore.mineForeman':'Armored foreman; silver cuts through his defenses.', 'lore.hollowEngine':'A moving grave of iron and coal.', 'lore.bellRinger':'His bell draws the dead; push him away.', 'lore.ghostSheriff':'A phantom who yields to spectral bullets.', 'lore.widowOfDust':'She weaves dust and fear across the last street.',
});
Object.assign(es,{
  version:'CAMPAÑA / 0.7',storyMode:'Modo historia',freeMode:'Supervivencia libre',arsenal:'Mazo Arsenal',bestiary:'Bestiario',
  deckCount:'{count}/{max} cartas equipadas',deckHint:'Elige al menos {min}; solo aparecen cartas equipadas.',equip:'Equipar',equipped:'Equipada',forge:'Combinar cartas',combine:'Combinar',forged:'Creada',equipIngredients:'Equipa ambos ingredientes',clearStage:'Completa {stage} en historia',
  unknownCreature:'Desconocido',discoverCreature:'Derrota a este enemigo para descubrirlo.',bestiaryCount:'{count}/{total} entradas descubiertas',creatures:'Criaturas',bosses:'Jefes',weakness:'Debilidad',counter:'Héroe que lo contrarresta',speed:'VELOCIDAD',armor:'ARMADURA',storyGoals:'Misiones + jefes',storyProgress:'Misiones {missions}/3 · Jefes {bosses}/3',storyClear:'¡Historia completada! Nueva fase y héroe desbloqueados.',storyIncomplete:'Historia incompleta: {missions}/{total} misiones, {bosses}/{all} jefes. Sobrevive y cumple todos los objetivos.',
  'hero.labuta':'Veterano corpulento con escopeta de tres perdigones. Resistente y lento.','hero.rosa':'Exploradora ferroviaria con dos revólveres y pies ligeros.','hero.elias':'Minero veterano con rifle perforante y armadura.','hero.silas':'Cazarrecompensas veloz que lanza dos cuchillos.',
  'weapon.whip':'Látigo','weapon.revolver':'Revólver','weapon.bow':'Arco','weapon.shotgun':'Escopeta triple','weapon.dual':'Revólveres dobles','weapon.rifle':'Rifle perforante','weapon.knives':'Cuchillos',
  'missionDog':'Elimina chupacabras','missionMiner':'Elimina espectros mineros',
  'ability.bulwark':'Bastión de Hierro','ability.inferno':'Fuego Impío','ability.silverStorm':'Tempestad de Plata',
  bulwarkDesc:'+2 de armadura y +10 de vida máxima por nivel.',infernoDesc:'Fuego y farol: +{damage} de daño/s y más alcance.',silverStormDesc:'Lluvia de plata: {count} disparos extra y +{damage} de daño.',
  'enemy.bat':'Murciélago nocturno','enemy.dog':'Chupacabras','enemy.vulture':'Buitre carroñero','enemy.skeleton':'Pistolero esqueleto','enemy.miner':'Espectro minero',
  'weakness.bat':'Ataques de área','weakness.dog':'Empujones','weakness.vulture':'Esquivar rutas marcadas','weakness.skeleton':'Flechas perforantes','weakness.miner':'Fuego',
  'boss.duneRider':'Jinete de las Dunas','boss.gravedigger':'Sepulturero Maldito','boss.shadowMarshal':'Alguacil Sombrío','boss.oreWraith':'Espectro del Mineral','boss.mineForeman':'Capataz de la Mina','boss.hollowEngine':'Máquina Hueca','boss.bellRinger':'Campanero','boss.ghostSheriff':'Sheriff Fantasma','boss.widowOfDust':'Viuda del Polvo',
  'lore.bat':'Vuelan en grupo; los arcos amplios los dispersan.','lore.dog':'Persigue de cerca y acelera rápido.','lore.vulture':'Carga por el camino marcado al aparecer.','lore.skeleton':'Dispara desde lejos; acércate de lado.','lore.miner':'Surge de túneles oscuros; teme el fuego.',
  'lore.duneRider':'Jinete perdido bajo la arena.','lore.gravedigger':'Aprieta su círculo de fuego: quema su armadura.','lore.shadowMarshal':'Ordena cargas brutales desde la arena.','lore.oreWraith':'La luz del farol maldito lo debilita.','lore.mineForeman':'Su armadura cede ante la plata.','lore.hollowEngine':'Una tumba móvil de hierro y carbón.','lore.bellRinger':'Su campana atrae muertos; empújalo lejos.','lore.ghostSheriff':'Cae ante balas espectrales.','lore.widowOfDust':'Teje polvo y miedo en la última calle.',
});
Object.assign(pt,{
  version:'CAMPANHA / 0.7',storyMode:'Modo história',freeMode:'Sobrevivência livre',arsenal:'Deck Arsenal',bestiary:'Bestiário',
  deckCount:'{count}/{max} cartas equipadas',deckHint:'Escolha pelo menos {min}; apenas cartas equipadas aparecem na partida.',equip:'Equipar',equipped:'Equipada',forge:'Juntar cartas',combine:'Juntar',forged:'Criada',equipIngredients:'Equipe os dois ingredientes',clearStage:'Conclua {stage} no modo história',
  unknownCreature:'Desconhecido',discoverCreature:'Derrote este inimigo para revelar sua história.',bestiaryCount:'{count}/{total} registros descobertos',creatures:'Criaturas',bosses:'Chefes',weakness:'Fraqueza',counter:'Campeão que o enfrenta melhor',speed:'VELOCIDADE',armor:'ARMADURA',storyGoals:'Missões + chefes',storyProgress:'Missões {missions}/3 · Chefes {bosses}/3',storyClear:'Campanha concluída! Uma fase e um campeão foram liberados.',storyIncomplete:'Campanha incompleta: {missions}/{total} missões, {bosses}/{all} chefes. Sobreviva e cumpra todos os objetivos.',
  'hero.labuta':'Veterano robusto da Guerra Civil, armado com escopeta de três chumbos. Resistente e lento.','hero.rosa':'Batedora da ferrovia com dois revólveres e passos velozes.','hero.elias':'Mineiro veterano, rifle perfurante e armadura resistente.','hero.silas':'Caçador de recompensas ágil que lança duas facas.',
  'weapon.whip':'Chicote','weapon.revolver':'Revólver','weapon.bow':'Arco','weapon.shotgun':'Escopeta tripla','weapon.dual':'Dois revólveres','weapon.rifle':'Rifle perfurante','weapon.knives':'Facas arremessadas',
  'missionDog':'Mate chupacabras','missionMiner':'Mate espectros da mina',
  'ability.bulwark':'Bastião de Ferro','ability.inferno':'Fogo Profano','ability.silverStorm':'Tempestade de Prata',
  bulwarkDesc:'+2 de armadura e +10 de vida máxima por nível.',infernoDesc:'Fogo e lampião causam +{damage} de dano/s e alcançam mais longe.',silverStormDesc:'Chuva de prata ganha {count} disparos e +{damage} de dano.',
  'enemy.bat':'Morcego noturno','enemy.dog':'Chupacabra','enemy.vulture':'Urubu carniceiro','enemy.skeleton':'Esqueleto pistoleiro','enemy.miner':'Espectro mineiro',
  'weakness.bat':'Ataques em área','weakness.dog':'Empurrão','weakness.vulture':'Desvie das rotas marcadas','weakness.skeleton':'Flechas perfurantes','weakness.miner':'Fogo',
  'boss.duneRider':'Cavaleiro das Dunas','boss.gravedigger':'Coveiro Maldito','boss.shadowMarshal':'Xerife das Sombras','boss.oreWraith':'Espectro do Minério','boss.mineForeman':'Capataz da Mina','boss.hollowEngine':'Engenho Oco','boss.bellRinger':'Sineiro das Trevas','boss.ghostSheriff':'Xerife Fantasma','boss.widowOfDust':'Viúva da Poeira',
  'lore.bat':'Atacam em bandos; um golpe amplo limpa o caminho.','lore.dog':'Caça rente ao solo e encurta a distância depressa.','lore.vulture':'Investe pela trilha marcada no surgimento.','lore.skeleton':'Atira de longe; avance pelas laterais.','lore.miner':'Surge da escuridão; o fogo atrapalha seu avanço.',
  'lore.duneRider':'Um cavaleiro soterrado pelas dunas; abre rotas perigosas.','lore.gravedigger':'Aperta o círculo de fogo: queime sua armadura.','lore.shadowMarshal':'Comanda investidas violentas da areia.','lore.oreWraith':'Assombra a mina e teme o lampião maldito.','lore.mineForeman':'Capataz blindado; a prata corta suas defesas.','lore.hollowEngine':'Uma tumba móvel de ferro e carvão.','lore.bellRinger':'Seu sino atrai mortos; afaste-o.','lore.ghostSheriff':'Um fantasma que cede às balas espectrais.','lore.widowOfDust':'Tece poeira e medo na última rua.',
});
Object.assign(en,{critical:'CRIT',experience:'XP'});
Object.assign(es,{critical:'CRÍTICO',experience:'EXP'});
Object.assign(pt,{critical:'CRÍTICO',experience:'EXP'});
Object.assign(en,{
  version:'FIVE STAGES / 0.7',storyClear:'Stage cleared! Check new rewards in selection and Bento’s Market.',chooseMode:'Choose your mode',storyIntro:'Clear quests and bosses to unlock the frontier.',freeIntro:'Play unlocked stages and heroes with your Arsenal deck.',freeLock:'Finish the Desert in Story mode to unlock.',progressionTools:'Arsenal and services',hiddenHero:'???',unknownStage:'Unknown stage',bentoCollection:'Bento’s exclusive cards',exclusiveBento:'EXCLUSIVE CARD',ownedCard:'Owned',encounteredBoss:'Encountered: full tactics unlocked after defeat.',bossStats:'HP {hp} · DAMAGE {damage} · ARMOR {armor} · SPEED {speed}',bossPattern:'Attack: {pattern}',
  'hero.ada':'Spirit tracker whose crossbow pierces armored targets.','hero.ruth':'Frontier demolition expert; two heavy shotgun pellets.','hero.teo':'Rail courier with a fast repeating rifle.',
  'weapon.crossbow':'Piercing crossbow','weapon.sawedoff':'Double barrel','weapon.repeater':'Repeating rifle',
  'map.canyon':'Ash Canyon','map.cemetery':'Frontier Necropolis','mapDesc.canyon':'Red cliffs, broken bridges and wandering ash wraiths.','mapDesc.cemetery':'Moonlit graves, restless crows and an abandoned chapel.',
  missionWraith:'Defeat ash wraiths',missionCrow:'Defeat grave crows',missionVulture:'Defeat vultures',
  'enemy.wraith':'Ash wraith','enemy.crow':'Grave crow','weakness.wraith':'Lantern fire','weakness.crow':'Wide area attacks',
  'ability.ironCharm':'Bento’s Iron Charm','ability.deadeye':'Lead Eye','ability.bloodOath':'Frontier Pact',
  ironCharmDesc:'+2 armor per rank; deflects a portion of hits.',deadeyeDesc:'+4 primary weapon damage per rank.',bloodOathDesc:'+12 maximum HP and slow recovery per rank.',
  'bentoDesc.ironCharm':'An armored talisman for your Arsenal deck.','bentoDesc.deadeye':'Permanent access to a precision card.','bentoDesc.bloodOath':'Permanent access to a healing card.',
  'shop.sharpshooter':'Bento’s Aim','shop.bounty':'Hunter’s Purse','shopDesc.sharpshooter':'+2.5% critical chance per purchase.','shopDesc.bounty':'+8% coins gathered per purchase.',
  'boss.giantBat':'Night Patriarch','boss.fireChupacabra':'Ember Chupacabra','boss.shovelMiner':'Shovel Miner','boss.giantMoth':'Vein Moth','boss.minerGeneral':'Miner General','boss.boneHound':'Bone Hound','boss.boneSinger':'Bone Singer','boss.zombieDeputy':'Zombie Deputy','boss.ashSerpent':'Ash Serpent','boss.stormVulture':'Storm Vulture','boss.railRevenant':'Rail Revenant','boss.cryptMother':'Crypt Mother','boss.deadPreacher':'Dead Preacher','boss.lastConductor':'Last Conductor',
  'lore.giantBat':'Slow giant bat with a ring of cursed projectiles.','lore.fireChupacabra':'Marks your last position before igniting it.','lore.shovelMiner':'Slow zombie miner; avoid its lunging shovel.','lore.giantMoth':'Marks your position before charging through it.','lore.minerGeneral':'Summons smaller undead miners to surround you.','lore.boneHound':'Slow pursuit followed by a marked lunge.','lore.boneSinger':'Sings skeleton gunfighters back to their feet.','lore.zombieDeputy':'Fires three shotgun pellets at your marked position.','lore.ashSerpent':'Its burning trail punishes stationary players.','lore.stormVulture':'Dives in a marked straight line.','lore.railRevenant':'Fires a spread over old tracks.','lore.cryptMother':'Raises undead miners from shallow graves.','lore.deadPreacher':'Calls skeletal followers around the player.','lore.lastConductor':'A final three-pellet burst guards the frontier.',
  'pattern.pulse':'Radial shots','pattern.fireMark':'Marked fire','pattern.lunge':'Marked lunge','pattern.dash':'Marked rush','pattern.summonMiner':'Summoned miners','pattern.summonSkeleton':'Summoned skeletons','pattern.shotgun':'Triple shotgun','pattern.volley':'Shot spread',
  storyProgress:'Quests {missions}/{total} · Bosses {bosses}/{all}',
});
Object.assign(es,{
  version:'CINCO FASES / 0.7',storyClear:'¡Fase superada! Revisa las recompensas y el mercado.',chooseMode:'Elige el modo',storyIntro:'Completa misiones y jefes para desbloquear el mundo.',freeIntro:'Juega con fases y personajes desbloqueados.',freeLock:'Completa el Desierto en modo historia.',progressionTools:'Arsenal y servicios',hiddenHero:'???',unknownStage:'Fase desconocida',bentoCollection:'Cartas exclusivas de Bento',exclusiveBento:'CARTA EXCLUSIVA',ownedCard:'Comprada',encounteredBoss:'Conocido: revela sus tácticas al derrotarlo.',bossStats:'VIDA {hp} · DAÑO {damage} · ARMADURA {armor} · VELOCIDAD {speed}',bossPattern:'Ataque: {pattern}',
  'hero.ada':'Cazadora de espíritus con ballesta perforante.','hero.ruth':'Experta en explosivos con escopeta de dos perdigones.','hero.teo':'Mensajero del ferrocarril con rifle de repetición.',
  'weapon.crossbow':'Ballesta perforante','weapon.sawedoff':'Escopeta doble','weapon.repeater':'Rifle de repetición',
  'map.canyon':'Cañón de Cenizas','map.cemetery':'Necrópolis de la Frontera','mapDesc.canyon':'Acantilados rojos y espectros de ceniza.','mapDesc.cemetery':'Tumbas a la luz de la luna y cuervos inquietos.',
  missionWraith:'Derrota espectros de ceniza',missionCrow:'Derrota cuervos',missionVulture:'Derrota buitres',
  'enemy.wraith':'Espectro de ceniza','enemy.crow':'Cuervo de tumba','weakness.wraith':'Fuego del farol','weakness.crow':'Ataques amplios',
  'ability.ironCharm':'Amuleto de Bento','ability.deadeye':'Ojo de Plomo','ability.bloodOath':'Pacto de la Frontera',
  ironCharmDesc:'+2 de armadura por nivel.',deadeyeDesc:'+4 de daño del arma principal por nivel.',bloodOathDesc:'+12 de vida máxima y recuperación lenta por nivel.',
  'bentoDesc.ironCharm':'Talismán blindado para tu Arsenal.','bentoDesc.deadeye':'Acceso permanente a una carta de precisión.','bentoDesc.bloodOath':'Acceso permanente a una carta de curación.',
  'shop.sharpshooter':'Puntería de Bento','shop.bounty':'Bolsa del Cazador','shopDesc.sharpshooter':'+2,5% de probabilidad crítica por compra.','shopDesc.bounty':'+8% de monedas recogidas por compra.',
  'boss.giantBat':'Patriarca de la Noche','boss.fireChupacabra':'Chupacabras de Brasas','boss.shovelMiner':'Minero de la Pala','boss.giantMoth':'Polilla de la Veta','boss.minerGeneral':'General Minero','boss.boneHound':'Perro de Hueso','boss.boneSinger':'Cantor Esqueleto','boss.zombieDeputy':'Delegado Zombi','boss.ashSerpent':'Serpiente de Ceniza','boss.stormVulture':'Buitre de Tormenta','boss.railRevenant':'Aparecido del Tren','boss.cryptMother':'Madre de la Cripta','boss.deadPreacher':'Predicador Muerto','boss.lastConductor':'Último Conductor',
  'lore.giantBat':'Murciélago gigante y lento; dispara en círculo.','lore.fireChupacabra':'Marca tu posición anterior antes de prenderla.','lore.shovelMiner':'Zombi lento que embiste con la pala.','lore.giantMoth':'Marca tu posición antes de avanzar.','lore.minerGeneral':'Invoca pequeños mineros zombis.','lore.boneHound':'Persigue lentamente antes de saltar.','lore.boneSinger':'Invoca esqueletos para seguirte.','lore.zombieDeputy':'Dispara tres perdigones a la posición marcada.','lore.ashSerpent':'Castiga quedarse quieto con fuego.','lore.stormVulture':'Embiste en línea recta marcada.','lore.railRevenant':'Dispara una ráfaga en las vías.','lore.cryptMother':'Levanta mineros zombis.','lore.deadPreacher':'Llama seguidores esqueléticos.','lore.lastConductor':'Tres balas protegen la frontera.',
  'pattern.pulse':'Disparos radiales','pattern.fireMark':'Fuego marcado','pattern.lunge':'Salto marcado','pattern.dash':'Embestida marcada','pattern.summonMiner':'Invoca mineros','pattern.summonSkeleton':'Invoca esqueletos','pattern.shotgun':'Escopeta triple','pattern.volley':'Ráfaga',
  storyProgress:'Misiones {missions}/{total} · Jefes {bosses}/{all}',
});
Object.assign(pt,{
  version:'CINCO FASES / 0.7',storyClear:'Fase concluída! Confira as recompensas na seleção e no mercador.',chooseMode:'Escolha o modo',storyIntro:'Cumpra missões e derrote chefes para avançar.',freeIntro:'Jogue com fases e campeões liberados.',freeLock:'Conclua o Deserto no modo história para liberar.',progressionTools:'Arsenal e serviços',hiddenHero:'???',unknownStage:'Fase desconhecida',bentoCollection:'Cartas exclusivas do Bento',exclusiveBento:'CARTA EXCLUSIVA',ownedCard:'Adquirida',encounteredBoss:'Encontrado: derrote para revelar todos os atributos.',bossStats:'VIDA {hp} · DANO {damage} · ARMADURA {armor} · VELOCIDADE {speed}',bossPattern:'Ataque: {pattern}',
  'hero.ada':'Caçadora de espíritos com besta perfurante.','hero.ruth':'Especialista em explosivos, escopeta de dois chumbos.','hero.teo':'Mensageiro da ferrovia com rifle de repetição.',
  'weapon.crossbow':'Besta perfurante','weapon.sawedoff':'Escopeta dupla','weapon.repeater':'Rifle de repetição',
  'map.canyon':'Desfiladeiro das Cinzas','map.cemetery':'Necrópole da Fronteira','mapDesc.canyon':'Penhascos vermelhos e espectros nas cinzas.','mapDesc.cemetery':'Sepulturas sob luar e corvos inquietos.',
  missionWraith:'Derrote espectros de cinza',missionCrow:'Derrote corvos das tumbas',missionVulture:'Derrote urubus',
  'enemy.wraith':'Espectro de cinzas','enemy.crow':'Corvo da tumba','weakness.wraith':'Fogo do lampião','weakness.crow':'Ataques amplos',
  'ability.ironCharm':'Amuleto de Bento','ability.deadeye':'Olho de Chumbo','ability.bloodOath':'Pacto da Fronteira',
  ironCharmDesc:'+2 de armadura por nível.',deadeyeDesc:'+4 de dano da arma principal por nível.',bloodOathDesc:'+12 de vida máxima e recuperação lenta por nível.',
  'bentoDesc.ironCharm':'Talismã blindado para o seu Deck Arsenal.','bentoDesc.deadeye':'Acesso permanente a uma carta de precisão.','bentoDesc.bloodOath':'Acesso permanente a uma carta de recuperação.',
  'shop.sharpshooter':'Mira do Bento','shop.bounty':'Bolsa do Caçador','shopDesc.sharpshooter':'+2,5% de chance crítica por compra.','shopDesc.bounty':'+8% de moedas coletadas por compra.',
  'boss.giantBat':'Patriarca da Noite','boss.fireChupacabra':'Chupacabra de Brasas','boss.shovelMiner':'Mineiro da Pá','boss.giantMoth':'Mariposa da Prata','boss.minerGeneral':'General Mineiro','boss.boneHound':'Cão de Ossos','boss.boneSinger':'Cantor Esqueleto','boss.zombieDeputy':'Delegado Zumbi','boss.ashSerpent':'Serpente das Cinzas','boss.stormVulture':'Urubu da Tempestade','boss.railRevenant':'Revenante dos Trilhos','boss.cryptMother':'Mãe da Cripta','boss.deadPreacher':'Pregador Morto','boss.lastConductor':'Último Condutor',
  'lore.giantBat':'Morcego gigante e lento; seus ataques formam um círculo.','lore.fireChupacabra':'Marca sua última posição antes de lançar fogo.','lore.shovelMiner':'Zumbi lento que investe com uma pá.','lore.giantMoth':'Marca sua posição antes de avançar.','lore.minerGeneral':'Invoca pequenos mineiros zumbis.','lore.boneHound':'Persegue devagar, então avança.','lore.boneSinger':'Invoca esqueletos para perseguir você.','lore.zombieDeputy':'Atira três chumbos no ponto marcado.','lore.ashSerpent':'O fogo pune jogadores parados.','lore.stormVulture':'Avança na linha marcada no chão.','lore.railRevenant':'Dispara em leque pelos trilhos.','lore.cryptMother':'Levanta mineiros de sepulturas rasas.','lore.deadPreacher':'Convoca seguidores esqueléticos.','lore.lastConductor':'Três chumbos protegem a última fronteira.',
  'pattern.pulse':'Tiros radiais','pattern.fireMark':'Fogo na posição marcada','pattern.lunge':'Investida marcada','pattern.dash':'Avanço marcado','pattern.summonMiner':'Invoca mineiros','pattern.summonSkeleton':'Invoca esqueletos','pattern.shotgun':'Escopeta tripla','pattern.volley':'Rajada em leque',
  storyProgress:'Missões {missions}/{total} · Chefes {bosses}/{all}',
});
Object.assign(en,{shopFilter:'Product categories',shopAll:'All',shopUpgrades:'Upgrades',shopCards:'Bento cards'});
Object.assign(es,{shopFilter:'Categorías de productos',shopAll:'Todo',shopUpgrades:'Mejoras',shopCards:'Cartas de Bento'});
Object.assign(pt,{shopFilter:'Categorias de mercadorias',shopAll:'Todos',shopUpgrades:'Melhorias',shopCards:'Cartas do Bento'});
const suits={
  en:{FERRO:'IRON',FOGO:'FIRE',VIDA:'HEALTH',SOMBRA:'SHADOW',ALMA:'SOUL',VENTO:'WIND',PRATA:'SILVER',MALDIÇÃO:'CURSE',OSSO:'BONE',DEFESA:'DEFENSE',CORAGEM:'COURAGE'},
  es:{FERRO:'HIERRO',FOGO:'FUEGO',VIDA:'VIDA',SOMBRA:'SOMBRA',ALMA:'ALMA',VENTO:'VIENTO',PRATA:'PLATA',MALDIÇÃO:'MALDICIÓN',OSSO:'HUESO',DEFESA:'DEFENSA',CORAGEM:'VALOR'},
  pt:{FERRO:'FERRO',FOGO:'FOGO',VIDA:'VIDA',SOMBRA:'SOMBRA',ALMA:'ALMA',VENTO:'VENTO',PRATA:'PRATA',MALDIÇÃO:'MALDIÇÃO',OSSO:'OSSO',DEFESA:'DEFESA',CORAGEM:'CORAGEM'},
};
const audioTexts={
  en:{audioLoading:'Loading and testing audio…',audioBlocked:'Audio blocked. Tap Test audio again.',audioDisabled:'Enable game sounds to hear the test.',audioUnavailable:'Could not load the shot sound. Check your connection and retry.',audioPartial:'Shot played, but {count} sound(s) failed. Tap to retry.',audioSuccess:'Shot played. Check your device volume and whether this tab is muted.',webglFailed:'Could not start 3D. Check WebGL and hardware acceleration in your browser.'},
  es:{audioLoading:'Cargando y probando sonidos…',audioBlocked:'Audio bloqueado. Pulsa Probar audio otra vez.',audioDisabled:'Activa los sonidos para escuchar la prueba.',audioUnavailable:'No se pudo cargar el disparo. Comprueba la conexión.',audioPartial:'Disparo reproducido, pero fallaron {count} sonido(s). Reintenta.',audioSuccess:'Disparo reproducido. Comprueba el volumen y si la pestaña está silenciada.',webglFailed:'No se pudo iniciar el 3D. Comprueba WebGL y la aceleración de hardware.'},
  pt:{audioLoading:'Carregando e testando os sons…',audioBlocked:'Áudio bloqueado. Toque novamente em Testar áudio.',audioDisabled:'Ative Sons do jogo para ouvir o teste.',audioUnavailable:'Não foi possível carregar o disparo. Verifique a conexão.',audioPartial:'Disparo reproduzido, mas {count} áudio(s) falharam. Tente novamente.',audioSuccess:'Disparo reproduzido. Verifique o volume e se esta aba está silenciada.',webglFailed:'Não foi possível iniciar o 3D. Verifique WebGL e a aceleração de hardware.'},
};
export function t(language,key,params={}) {
  const template=key.startsWith('suit.')?(suits[language]?.[key.slice(5)]??key.slice(5)):(audioTexts[language]?.[key]??audioTexts.en[key]??dictionary[language]?.[key]??en[key]??key);
  return template.replace(/\{(\w+)\}/g,(_,field)=>String(params[field]??''));
}
export function localizedCardDescription(language,id,level,attackRate=1){
  const stats=abilityStats(id,level);
  const values={...stats,damage:stats.damage,attack:Math.round((stats.attack||0)*100),
    cooldown:stats.cooldown?Math.max(0.15,stats.cooldown/attackRate).toFixed(2):'',
    radius:stats.radius?.toFixed(1),duration:stats.duration?.toFixed(2)};
  return t(language,(id==='heart'?'health':id)+'Desc',values);
}
