import {abilityStats} from '../config/abilityConfig.js';
export const LANGUAGES={en:'English (US)',es:'Español',pt:'Português (Brasil)'};
const en={
  menu:'Main menu',character:'Character',stage:'Stage',steps:'Steps',prepare:'PREPARE YOUR JOURNEY',chooseCharacter:'Choose your character',chooseMap:'Choose your stage',continue:'Continue',play:'Ride into the fray',life:'HEALTH',damage:'DAMAGE',duration:'DURATION',minutes:'minutes',coins:'coins',market:"Bento's Market",permanentUpgrades:'Permanent upgrades',permanentHelp:'Market upgrades stay with you in every run.',controlsHelp:'WASD / arrows or touch control. Automatic attacks.',
  'hero.joao':'Weathered leather, trusty whip and nerves of steel.','hero.maria':'A lightning quick gunslinger with a faithful revolver.','hero.indigo':'A skilled desert archer whose arrows pierce the darkness.',
  'map.desert':'Desert of the Forgotten','map.mine':'Nightfall Mine','map.town':'Ghost Town',
  'mapDesc.desert':'Open dunes, cacti and vultures under a relentless sun.','mapDesc.mine':'Dark galleries, ore carts and glowing lantern posts.','mapDesc.town':'An abandoned western town full of boarded shops and restless dead.',
  est:'EST. 1887 / LAWLESS LANDS',chapter:'CHAPTER ONE',tag:'ONE LAST CHANCE UNDER THE SUN',tagline:'The desert does not bury its dead.<br>It brings them back.',newGame:'New game',settings:'Settings',exit:'Exit',survive:'SURVIVE UNTIL THE LAST SUNSET',footer:'A SURVIVOR IN THE OLD WEST',version:'TWO CURSED BOSSES / 0.6',settingsTitle:'Settings',settingsIntro:'TUNE YOUR JOURNEY',wind:'Menu wind',sound:'Game sounds',music:'Western music',motion:'The menu respects reduced motion settings.',back:'Back',backMenu:'Back to menu',testAudio:'Test audio / retry',audioHelp:'Audio starts after a click, tap or keypress. Check your device volume.',goodbye:'UNTIL NEXT TIME, STRANGER',farewell:'The desert awaits.',closeTab:'You may close this tab or go back to the menu.',saved:'Preference saved.',saveFailed:'Applied for this session; saving is unavailable.',language:'Language',
  countdown:'TIME LEFT',pause:'Pause game',resume:'Continue',quitRun:'End run',level:'LEVEL',runCoins:'Run',warningVultures:'⚠ Vultures incoming! Dodge the marked path!',merchantHint:'Bento {arrow} · {distance} m · leaves in {time}s · come closer to trade',bossFire:'CURSED GRAVEDIGGER · FIRE RING',bossMarshal:'SHADOW MARSHAL · FIRE RING',bossLife:'{hp} / {max} HP · Stay away from the flames',mission:'SIDE QUEST',missionBat:'Defeat bats',missionCrate:'Break crates',missionSkeleton:'Defeat skeleton gunfighters',missionTime:'{time}s remaining',missionFailed:'Side quest failed',stormWarning:'DUST STORM · AVOID THE TORNADOES!',
  perkAlert:'LEVEL {level} · YOUR LEGEND GROWS',pauseTitle:'Take a breath, outlaw',paused:'RUN PAUSED',resumeButton:'Continue',endButton:'End and return',winIntro:'THE SUN RISES FOR THE STRONG',loseIntro:'THE DUST COVERS ANOTHER TALE',winTitle:'You survived!',loseTitle:'End of the trail',retry:'Play again',backSelect:'Return to selection',statSummary:'{kills} enemies · Level {level}',coinsSaved:'{coins} coins banked',coinsSession:'Balance available only this session.',
  missionSuccess:'QUEST COMPLETE',chooseReward:'Pick your reward',missionCard:'Upgrade a card',missionCoins:'+25 run coins',missionHealth:'+20 max HP and heal 40',chooseCard:'Upgrade this card',
  shopTitle:'BENTO’S MARKET',savedCoins:'◈ {coins} saved',merchantName:'BENTO, THE WANDERER',merchantTitle:'Prepare for<br>your next journey.',merchantSays:'“What you buy here stays with you.”',merchantThanks:'“A fine deal, traveler.” This upgrade lasts for this run.',merchantThanksForever:'“Thank you, traveler. This upgrade is yours for good.”',shopPermanent:'PERMANENT UPGRADES',shopFoot:'Uses only saved coins. Each product costs more after each purchase.',buy:'Buy · ◈ {price}',limit:'Limit reached',permanent:'PERMANENT · RANK {rank}',runShopIntro:'BENTO IN THE WILDS · RUN PAUSED',runShopTitle:'Supplies for the road',runMoney:'◈ {coins} coins from this run · separate from your saved balance.',runShopHelp:'These purchases last for this run only. Only cards you own are listed.',runRank:'THIS RUN · {type} {rank}',runLevel:'RANK',runUpgrade:'UPGRADES',leaveMerchant:'Back to the fight →',haste:'Quick Trigger',spur:'Wanderer’s Spurs',primaryShop:'Primary Weapon',primaryDesc:'+3 damage. Next damage: {damage}.',hasteDesc:'+6% attack speed this run.',spurDesc:'+5% move speed this run.',
  cardHeading:'Write your fate.',cardPending:'LEVEL {level} · {choices} CHOICE(S) LEFT',cardPrompt:'Choose one card. The run pauses while you decide.',unlock:'UNLOCK',evolve:'UPGRADE',grade:'RANK',combo:'CHAIN',comboStart:'Starts a new chain.',comboHealth:'Heal {heal} extra HP.',comboDamage:'+{damage}% damage for 20 s.',deckRule:'THE OUTLAW DECK · Change cards to build a chain up to three. Repeating strengthens a card and restarts the chain.',
  'ability.pistol':'Frontier Revolver','ability.molotov':'Molotov Cocktail','ability.heart':'Cowboy Heart','ability.horseshoe':'Cursed Horseshoes','ability.ghostShot':'Ghost Bullet','ability.requiem':'Dust Requiem','ability.silverRain':'Silver Rain','ability.lantern':'Cursed Lantern','ability.soulHarvest':'Soul Harvest','ability.boneStorm':'Bone Storm','ability.ironWill':'Iron Will','ability.lastStand':'Last Shot',
  'shop.health':'Cowboy Heart','shop.attack':'Quick Hands','shop.movement':'Desert Stride','shop.primary':'Leather and Steel','shop.armor':'Reinforced Leather','shop.magnet':'Prospector’s Magnet',
  'shopDesc.health':'+20 starting HP per purchase.','shopDesc.attack':'+8% attack speed per purchase (all weapons).','shopDesc.movement':'+5% movement speed per purchase.','shopDesc.primary':'+2 base damage for your hero’s primary weapon.','shopDesc.armor':'+2 starting armor per purchase.','shopDesc.magnet':'+0.7 pickup radius per purchase.',
  healthDesc:'+20 max HP and heal 20 for this run.',pistolDesc:'{damage} damage · one shot every {cooldown}s.',molotovDesc:'{damage} damage/s · fire for {duration}s · throw every {cooldown}s.',horseshoeDesc:'{count} orbiting horseshoes · {damage} contact damage.',ghostShotDesc:'{damage} damage · pierces {pierce} enemies · every {cooldown}s.',requiemDesc:'Dust wave {radius} m · {damage} damage and knockback · every {cooldown}s.',silverRainDesc:'{count} radial bullets · {damage} damage each · every {cooldown}s.',lanternDesc:'Cursed glow burns nearby enemies: {damage} damage/s in {radius} m.',soulHarvestDesc:'Heal {heal} HP per kill (up to maximum).',boneStormDesc:'{count} bone shards · {damage} damage · every {cooldown}s.',ironWillDesc:'+3 armor this run · {armor} armor from this card in total.',lastStandDesc:'Below 35% HP: +{attack}% attack speed.',
};
const es={
  menu:'Menú principal',character:'Personaje',stage:'Escenario',steps:'Pasos',prepare:'PREPARA TU VIAJE',chooseCharacter:'Elige tu personaje',chooseMap:'Elige tu escenario',continue:'Continuar',play:'Comenzar partida',life:'VIDA',damage:'DAÑO',duration:'DURACIÓN',minutes:'minutos',coins:'monedas',market:'Mercado de Bento',permanentUpgrades:'Mejoras permanentes',permanentHelp:'Las mejoras del mercado duran todas las partidas.',controlsHelp:'WASD / flechas o control táctil. Ataques automáticos.',
  'hero.joao':'Cuero gastado, látigo fiel y nervios de acero.','hero.maria':'Pistolera veloz con un revólver de confianza.','hero.indigo':'Arquero del desierto cuyas flechas atraviesan la oscuridad.',
  'map.desert':'Desierto de los Olvidados','map.mine':'Mina de la Noche','map.town':'Pueblo Fantasma','mapDesc.desert':'Dunas, cactus y buitres bajo un sol implacable.','mapDesc.mine':'Galerías oscuras, vagonetas y postes iluminados.','mapDesc.town':'Pueblo del viejo oeste con tiendas tapiadas y muertos inquietos.',
  est:'EST. 1887 / TIERRAS SIN LEY',chapter:'CAPÍTULO UNO',tag:'UNA ÚLTIMA OPORTUNIDAD BAJO EL SOL',tagline:'El desierto no entierra a sus muertos.<br>Los devuelve.',newGame:'Nueva partida',settings:'Configuración',exit:'Salir',survive:'SOBREVIVE HASTA EL ÚLTIMO ATARDECER',footer:'UN SURVIVOR EN EL VIEJO OESTE',version:'DOS JEFES MALDITOS / 0.6',settingsTitle:'Configuración',settingsIntro:'AJUSTA TU VIAJE',wind:'Viento del menú',sound:'Sonidos del juego',music:'Música del oeste',motion:'El menú respeta la preferencia de movimiento reducido.',back:'Volver',backMenu:'Volver al menú',testAudio:'Probar audio / reintentar',audioHelp:'El audio comienza tras un clic, toque o tecla. Comprueba el volumen.',goodbye:'HASTA LA PRÓXIMA, FORASTERO',farewell:'El desierto espera.',closeTab:'Puedes cerrar la pestaña o volver al menú.',saved:'Preferencia guardada.',saveFailed:'Aplicado en esta sesión; no se pudo guardar.',language:'Idioma',
  countdown:'TIEMPO RESTANTE',pause:'Pausar partida',resume:'Continuar',quitRun:'Terminar partida',level:'NIVEL',runCoins:'Partida',warningVultures:'⚠ ¡Buitres a la vista! ¡Esquiva el camino marcado!',merchantHint:'Bento {arrow} · {distance} m · se va en {time}s · acércate para comerciar',bossFire:'SEPULTURERO MALDITO · CÍRCULO DE FUEGO',bossMarshal:'ALGUACIL DE LAS SOMBRAS · CÍRCULO DE FUEGO',bossLife:'{hp} / {max} VIDA · No toques las llamas',mission:'MISIÓN SECUNDARIA',missionBat:'Elimina murciélagos',missionCrate:'Rompe cajas',missionSkeleton:'Elimina pistoleros esqueleto',missionTime:'quedan {time}s',missionFailed:'Misión fallida',stormWarning:'TORMENTA DE POLVO · ¡ESQUIVA LOS TORNADOS!',perkAlert:'NIVEL {level} · CRECE TU LEYENDA',pauseTitle:'Respira, forastero',paused:'PARTIDA PAUSADA',resumeButton:'Continuar',endButton:'Terminar y volver',winIntro:'EL SOL SALE PARA LOS FUERTES',loseIntro:'EL POLVO CUBRE OTRA HISTORIA',winTitle:'¡Sobreviviste!',loseTitle:'Fin del camino',retry:'Jugar de nuevo',backSelect:'Volver a la selección',statSummary:'{kills} enemigos · Nivel {level}',coinsSaved:'{coins} monedas guardadas',coinsSession:'Saldo disponible solo en esta sesión.',
  missionSuccess:'MISIÓN CUMPLIDA',chooseReward:'Elige tu recompensa',missionCard:'Mejorar una carta',missionCoins:'+25 monedas de partida',missionHealth:'+20 vida máxima y recuperar 40',chooseCard:'Mejorar esta carta',
  shopTitle:'MERCADO DE BENTO',savedCoins:'◈ {coins} guardadas',merchantName:'BENTO, EL ANDARIEGO',merchantTitle:'Prepárate para<br>el próximo viaje.',merchantSays:'«Lo que compras aquí te acompaña».',merchantThanks:'«Buen trato, viajero». Esta mejora dura esta partida.',merchantThanksForever:'«Gracias, viajero». Esta mejora es tuya para siempre.',shopPermanent:'MEJORAS PERMANENTES',shopFoot:'Usa solo monedas guardadas. Los precios suben con cada compra.',buy:'Comprar · ◈ {price}',limit:'Límite alcanzado',permanent:'PERMANENTE · NIVEL {rank}',runShopIntro:'BENTO EN EL PÁRAMO · PARTIDA PAUSADA',runShopTitle:'Suministros para el camino',runMoney:'◈ {coins} monedas de esta partida · saldo separado del menú.',runShopHelp:'Las compras duran solo esta partida. Aparecen solo las cartas adquiridas.',runRank:'ESTA PARTIDA · {type} {rank}',runLevel:'NIVEL',runUpgrade:'MEJORAS',leaveMerchant:'Volver a la partida →',haste:'Gatillo Veloz',spur:'Espuelas del Andariego',primaryShop:'Arma principal',primaryDesc:'+3 de daño. Próximo daño: {damage}.',hasteDesc:'+6% de velocidad de ataque esta partida.',spurDesc:'+5% de movimiento esta partida.',
  cardHeading:'Escribe tu destino.',cardPending:'NIVEL {level} · {choices} ELECCIÓN(ES) PENDIENTE(S)',cardPrompt:'Elige una carta. La partida se detiene mientras decides.',unlock:'DESBLOQUEAR',evolve:'MEJORAR',grade:'GRADO',combo:'RACHA',comboStart:'Inicia una nueva racha.',comboHealth:'Cura {heal} de vida extra.',comboDamage:'+{damage}% de daño durante 20 s.',deckRule:'BARAJA DEL DESIERTO · Alternar cartas aumenta la racha hasta tres. Repetir mejora la carta y reinicia la racha.',
  'ability.pistol':'Pistola del Desierto','ability.molotov':'Cóctel Molotov','ability.heart':'Corazón de Vaquero','ability.horseshoe':'Herraduras Malditas','ability.ghostShot':'Bala Fantasma','ability.requiem':'Réquiem de Polvo','ability.silverRain':'Lluvia de Plata','ability.lantern':'Farol Maldito','ability.soulHarvest':'Cosecha de Almas','ability.boneStorm':'Tormenta de Huesos','ability.ironWill':'Voluntad de Hierro','ability.lastStand':'Último Disparo',
  'shop.health':'Corazón de Vaquero','shop.attack':'Manos Rápidas','shop.movement':'Paso del Desierto','shop.primary':'Cuero y Acero','shop.armor':'Cuero Reforzado','shop.magnet':'Imán del Minero',
  'shopDesc.health':'+20 de vida inicial por compra.','shopDesc.attack':'+8% de velocidad de ataque por compra.','shopDesc.movement':'+5% de movimiento por compra.','shopDesc.primary':'+2 de daño base al arma principal.','shopDesc.armor':'+2 de armadura inicial por compra.','shopDesc.magnet':'+0,7 al radio de recolección por compra.',
  healthDesc:'+20 de vida máxima y recupera 20.',pistolDesc:'{damage} de daño · disparo cada {cooldown}s.',molotovDesc:'{damage} de daño/s · fuego por {duration}s · lanzamiento cada {cooldown}s.',horseshoeDesc:'{count} herraduras giratorias · {damage} de daño por contacto.',ghostShotDesc:'{damage} de daño · atraviesa {pierce} enemigos · cada {cooldown}s.',requiemDesc:'Onda de polvo de {radius} m · {damage} de daño y empuje · cada {cooldown}s.',silverRainDesc:'{count} balas radiales · {damage} de daño · cada {cooldown}s.',lanternDesc:'La luz maldita quema enemigos: {damage} de daño/s en {radius} m.',soulHarvestDesc:'Recupera {heal} de vida por baja (hasta el máximo).',boneStormDesc:'{count} huesos · {damage} de daño · cada {cooldown}s.',ironWillDesc:'+3 de armadura esta partida · {armor} de la carta en total.',lastStandDesc:'Con menos de 35% de vida: +{attack}% de velocidad de ataque.',
};
const pt={
  menu:'Menu principal',character:'Personagem',stage:'Fase',steps:'Etapas',prepare:'PREPARE SUA JORNADA',chooseCharacter:'Escolha seu personagem',chooseMap:'Escolha sua fase',continue:'Continuar',play:'Jogar',life:'VIDA',damage:'DANO',duration:'DURAÇÃO',minutes:'minutos',coins:'moedas',market:'Mercado do Bento',permanentUpgrades:'Melhorias permanentes',permanentHelp:'As melhorias do mercado acompanham você em todas as partidas.',controlsHelp:'WASD / setas ou controle por toque. Ataques automáticos.',
  'hero.joao':'Couro gasto, chicote fiel e coragem de sobra.','hero.maria':'Pistoleira veloz com seu revólver de confiança.','hero.indigo':'Arqueiro do deserto cujas flechas atravessam a escuridão.',
  'map.desert':'Deserto dos Esquecidos','map.mine':'Mina da Noite','map.town':'Cidade Fantasma','mapDesc.desert':'Dunas, cactos e urubus sob um sol implacável.','mapDesc.mine':'Galerias escuras, vagonetes e postes com lampiões.','mapDesc.town':'Cidade abandonada de velho oeste, lojas fechadas e mortos inquietos.',
  est:'EST. 1887 / TERRAS SEM LEI',chapter:'CAPÍTULO UM',tag:'UM SOL IMPLACÁVEL. UMA ÚLTIMA CHANCE.',tagline:'O deserto não enterra seus mortos.<br>Ele os devolve.',newGame:'Novo jogo',settings:'Configurações',exit:'Sair',survive:'SOBREVIVA ATÉ O ÚLTIMO PÔR DO SOL',footer:'UM SURVIVOR NO VELHO OESTE',version:'DOIS CHEFES MALDITOS / 0.6',settingsTitle:'Configurações',settingsIntro:'AJUSTE SUA JORNADA',wind:'Vento do menu',sound:'Sons do jogo',music:'Música de faroeste',motion:'O cenário respeita a preferência de movimento reduzido.',back:'Voltar',backMenu:'Voltar ao menu',testAudio:'Testar áudio / tentar novamente',audioHelp:'O som começa após clique, toque ou tecla. Verifique o volume.',goodbye:'ATÉ A PRÓXIMA, FORASTEIRO',farewell:'O deserto espera.',closeTab:'Você pode fechar esta aba ou voltar ao menu.',saved:'Preferência salva.',saveFailed:'Aplicado nesta sessão; salvamento indisponível.',language:'Idioma',
  countdown:'TEMPO RESTANTE',pause:'Pausar partida',resume:'Continuar',quitRun:'Encerrar partida',level:'NÍVEL',runCoins:'Partida',warningVultures:'⚠ Bando de urubus! Saia da rota marcada!',merchantHint:'Bento {arrow} · {distance} m · parte em {time}s · aproxime-se para negociar',bossFire:'COVEIRO MALDITO · ARENA EM CHAMAS',bossMarshal:'XERIFE DAS SOMBRAS · ARENA EM CHAMAS',bossLife:'{hp} / {max} VIDA · Não toque nas chamas',mission:'MISSÃO SECUNDÁRIA',missionBat:'Mate morcegos',missionCrate:'Quebre caixas',missionSkeleton:'Mate esqueletos pistoleiros',missionTime:'restam {time}s',missionFailed:'Missão secundária falhou',stormWarning:'TEMPESTADE DE AREIA · DESVIE DOS TORNADOS!',perkAlert:'NÍVEL {level} · A LENDA CRESCE',pauseTitle:'Respire, forasteiro',paused:'PARTIDA PAUSADA',resumeButton:'Continuar',endButton:'Encerrar e voltar',winIntro:'O SOL NASCE PARA OS FORTES',loseIntro:'A POEIRA COBRE MAIS UMA HISTÓRIA',winTitle:'Você sobreviveu!',loseTitle:'Fim da jornada',retry:'Jogar novamente',backSelect:'Voltar à seleção',statSummary:'{kills} inimigos · Nível {level}',coinsSaved:'{coins} moedas guardadas',coinsSession:'Saldo disponível apenas nesta sessão.',
  missionSuccess:'MISSÃO CUMPRIDA',chooseReward:'Escolha sua recompensa',missionCard:'Evoluir uma carta',missionCoins:'+25 moedas da partida',missionHealth:'+20 de vida máxima e cura 40',chooseCard:'Evoluir esta carta',
  shopTitle:'MERCADO DO BENTO',savedCoins:'◈ {coins} guardadas',merchantName:'BENTO, O ANDARILHO',merchantTitle:'Prepare-se para<br>a próxima jornada.',merchantSays:'“O que você compra aqui fica com você.”',merchantThanks:'“Bom negócio, viajante.” Melhoria aplicada somente nesta partida.',merchantThanksForever:'“Obrigado, viajante.” Esta melhoria fica com você.',shopPermanent:'MELHORIAS PERMANENTES',shopFoot:'Usa apenas moedas guardadas. Cada produto fica mais caro a cada compra.',buy:'Comprar · ◈ {price}',limit:'Limite atingido',permanent:'PERMANENTE · NÍVEL {rank}',runShopIntro:'BENTO NO DESERTO · PARTIDA PAUSADA',runShopTitle:'Um reforço para a jornada',runMoney:'◈ {coins} moedas desta partida · saldo separado do menu.',runShopHelp:'As compras duram somente esta partida. Apenas habilidades adquiridas aparecem.',runRank:'SÓ NESTA PARTIDA · {type} {rank}',runLevel:'NÍVEL',runUpgrade:'MELHORIAS',leaveMerchant:'Voltar à partida →',haste:'Tambor Acelerado',spur:'Esporas do Andarilho',primaryShop:'Arma principal',primaryDesc:'+3 de dano. Próximo dano: {damage}.',hasteDesc:'+6% de velocidade de ataque nesta partida.',spurDesc:'+5% de movimento nesta partida.',
  cardHeading:'Escreva seu destino.',cardPending:'NÍVEL {level} · {choices} ESCOLHA(S) PENDENTE(S)',cardPrompt:'Escolha uma carta. A partida fica parada enquanto decide.',unlock:'DESBLOQUEAR',evolve:'EVOLUIR',grade:'GRAU',combo:'SEQUÊNCIA',comboStart:'Inicia uma nova sequência.',comboHealth:'Cura extra de {heal} de vida.',comboDamage:'+{damage}% de dano por 20 s.',deckRule:'TRINCA DO SERTÃO · Alternar cartas aumenta a sequência até 3. Repetir melhora a carta e reinicia a sequência.',
  'ability.pistol':'Pistola do Sertão','ability.molotov':'Coquetel Molotov','ability.heart':'Coração de Vaqueiro','ability.horseshoe':'Ferraduras Malditas','ability.ghostShot':'Bala Fantasma','ability.requiem':'Réquiem da Poeira','ability.silverRain':'Chuva de Prata','ability.lantern':'Lampião Maldito','ability.soulHarvest':'Colheita de Almas','ability.boneStorm':'Estilhaços de Ossos','ability.ironWill':'Vontade de Ferro','ability.lastStand':'Último Disparo',
  'shop.health':'Coração de Vaqueiro','shop.attack':'Mãos Ligeiras','shop.movement':'Passo do Sertão','shop.primary':'Couro e Aço','shop.armor':'Couro Reforçado','shop.magnet':'Ímã do Garimpo',
  'shopDesc.health':'+20 de vida inicial por compra.','shopDesc.attack':'+8% de velocidade de ataque por compra.','shopDesc.movement':'+5% de movimento por compra.','shopDesc.primary':'+2 de dano base à arma principal.','shopDesc.armor':'+2 de armadura inicial por compra.','shopDesc.magnet':'+0,7 de raio de atração por compra.',
  healthDesc:'+20 de vida máxima e recupera 20 nesta partida.',pistolDesc:'{damage} de dano · tiro a cada {cooldown}s.',molotovDesc:'{damage} de dano/s · fogo por {duration}s · arremesso a cada {cooldown}s.',horseshoeDesc:'{count} ferraduras giratórias · {damage} de dano por contato.',ghostShotDesc:'{damage} de dano · atravessa {pierce} inimigos · a cada {cooldown}s.',requiemDesc:'Onda de poeira de {radius} m · {damage} de dano e empurrão · a cada {cooldown}s.',silverRainDesc:'{count} balas em círculo · {damage} de dano · a cada {cooldown}s.',lanternDesc:'A luz profana queima inimigos: {damage} de dano/s em {radius} m.',soulHarvestDesc:'Recupera {heal} de vida ao abater um inimigo.',boneStormDesc:'{count} estilhaços · {damage} de dano · a cada {cooldown}s.',ironWillDesc:'+3 de armadura nesta partida · {armor} da carta no total.',lastStandDesc:'Abaixo de 35% da vida: +{attack}% de velocidade de ataque.',
};
const dictionary={en,es,pt};
Object.assign(en,{'shop.fortune':'Prospector’s Fortune','shop.learning':'Legend’s Apprentice','shopDesc.fortune':'+4 percentage points to crate bandage chance per purchase.','shopDesc.learning':'+5% experience gained per purchase.'});
Object.assign(es,{'shop.fortune':'Suerte del Minero','shop.learning':'Aprendiz de Leyenda','shopDesc.fortune':'+4 puntos de probabilidad de vendas en cajas por compra.','shopDesc.learning':'+5% de experiencia obtenida por compra.'});
Object.assign(pt,{'shop.fortune':'Sorte de Garimpeiro','shop.learning':'Lenda Aprendiz','shopDesc.fortune':'+4 pontos na chance de bandagem por caixa a cada compra.','shopDesc.learning':'+5% de experiência recebida por compra.'});
const suits={
  en:{FERRO:'IRON',FOGO:'FIRE',VIDA:'HEALTH',SOMBRA:'SHADOW',ALMA:'SOUL',VENTO:'WIND',PRATA:'SILVER',MALDIÇÃO:'CURSE',OSSO:'BONE',DEFESA:'DEFENSE',CORAGEM:'COURAGE'},
  es:{FERRO:'HIERRO',FOGO:'FUEGO',VIDA:'VIDA',SOMBRA:'SOMBRA',ALMA:'ALMA',VENTO:'VIENTO',PRATA:'PLATA',MALDIÇÃO:'MALDICIÓN',OSSO:'HUESO',DEFESA:'DEFENSA',CORAGEM:'VALOR'},
  pt:{FERRO:'FERRO',FOGO:'FOGO',VIDA:'VIDA',SOMBRA:'SOMBRA',ALMA:'ALMA',VENTO:'VENTO',PRATA:'PRATA',MALDIÇÃO:'MALDIÇÃO',OSSO:'OSSO',DEFESA:'DEFESA',CORAGEM:'CORAGEM'},
};
const audioTexts={
  en:{audioLoading:'Loading and testing audio…',audioBlocked:'Audio blocked. Tap Test audio again.',audioDisabled:'Enable game sounds to hear the test.',audioUnavailable:'Could not load the shot sound. Check your connection and retry.',audioPartial:'Shot played, but {count} sound(s) failed. Tap to retry.',audioSuccess:'Shot played. Check your device volume and whether this tab is muted.',webglFailed:'Could not start 3D. Check WebGL and hardware acceleration in your browser.'},
  es:{audioLoading:'Cargando y probando sonidos…',audioBlocked:'Audio bloqueado. Pulsa Probar audio otra vez.',audioDisabled:'Activa los sonidos para escuchar la prueba.',audioUnavailable:'No se pudo cargar el disparo. Comprueba la conexión.',audioPartial:'Disparo reproducido, pero fallaron {count} sonido(s). Reintenta.',audioSuccess:'Disparo reproducido. Comprueba el volumen y si la pestaña está silenciada.',webglFailed:'No se pudo iniciar el 3D. Comprueba WebGL y la aceleración de hardware.'},
  pt:{audioLoading:'Carregando e testando os sons…',audioBlocked:'Áudio bloqueado. Toque novamente em Testar áudio.',audioDisabled:'Ative Sons do jogo para ouvir o teste.',audioUnavailable:'Não foi possível carregar o disparo. Verifique a conexão.',audioPartial:'Disparo reproduzido, mas {count} áudio(s) falharam. Tente novamente.',audioSuccess:'Disparo reproduzido. Verifique o volume e se esta aba está silenciada.',webglFailed:'Não foi possível iniciar o 3D. Verifique WebGL e a aceleração de hardware.'},
};
export function t(language,key,params={}) {
  const template=key.startsWith('suit.')?(suits[language]?.[key.slice(5)]??key.slice(5)):(audioTexts[language]?.[key]??audioTexts.en[key]??dictionary[language]?.[key]??en[key]??key);
  return template.replace(/\{(\w+)\}/g,(_,field)=>String(params[field]??''));
}
export function localizedCardDescription(language,id,level,attackRate=1){
  const stats=abilityStats(id,level);
  const values={...stats,damage:stats.damage,attack:Math.round((stats.attack||0)*100),
    cooldown:stats.cooldown?Math.max(0.15,stats.cooldown/attackRate).toFixed(2):'',
    radius:stats.radius?.toFixed(1),duration:stats.duration?.toFixed(2)};
  return t(language,(id==='heart'?'health':id)+'Desc',values);
}
