import joao from "../assets/portraits/heroic/joao.webp";
import maria from "../assets/portraits/heroic/maria.webp";
import indigo from "../assets/portraits/heroic/indigo.webp";
import labuta from "../assets/portraits/heroic/labuta.webp";
import rosa from "../assets/portraits/heroic/rosa.webp";
import elias from "../assets/portraits/heroic/elias.webp";
import silas from "../assets/portraits/heroic/silas.webp";
import ada from "../assets/portraits/heroic/ada.webp";
import ruth from "../assets/portraits/heroic/ruth.webp";
import teo from "../assets/portraits/heroic/teo.webp";
import valeria from "../assets/portraits/heroic/valeria.webp";
import tomas from "../assets/portraits/heroic/tomas.webp";
import luzia from "../assets/portraits/heroic/luzia.webp";
import benicio from "../assets/portraits/heroic/benicio.webp";
import ines from "../assets/portraits/heroic/ines.webp";
import dynamite from "../assets/portraits/heroic/dynamite.webp";
import jacinto from "../assets/portraits/heroic/jacinto.webp";
import aurora from "../assets/portraits/heroic/aurora.webp";
import gaspar from "../assets/portraits/heroic/gaspar.webp";
import celeste from "../assets/portraits/heroic/celeste.webp";
import severino from "../assets/portraits/heroic/severino.webp";
import amara from "../assets/portraits/heroic/amara.webp";
import clanker from "../assets/portraits/heroic/clanker.webp";
import bento from "../assets/portraits/bento-menu.webp";

export const HERO_PORTRAITS = { joao, maria, indigo, labuta, rosa, elias, silas, ada, ruth, teo, valeria, tomas, luzia, benicio, ines, dynamite, jacinto, aurora, gaspar, celeste, severino, amara, clanker };
export const BENTO_PORTRAIT = bento;
