import joao from "../assets/portraits/joao.webp";
import maria from "../assets/portraits/maria.webp";
import indigo from "../assets/portraits/indigo.webp";
import bento from "../assets/portraits/bento-menu.webp";
import labuta from "../assets/portraits/labuta.webp";
import rosa from "../assets/portraits/rosa.webp";
import elias from "../assets/portraits/elias.webp";
import silas from "../assets/portraits/silas-art-v3.webp";
import ada from "../assets/portraits/ada-art-v3.webp";
import ruth from "../assets/portraits/ruth-art-v3.webp";
import teo from "../assets/portraits/teo-art-v3.webp";
import valeria from "../assets/portraits/valeria-art-v3.webp";
import tomas from "../assets/portraits/tomas-art-v3.webp";
import luzia from "../assets/portraits/luzia-art-v3.webp";
import benicio from "../assets/portraits/benicio-art-v3.webp";
import ines from "../assets/portraits/ines-art-v3.webp";
import dynamite from "../assets/portraits/dynamite-art-v3.webp";
import jacinto from "../assets/portraits/jacinto-frontier.webp";
import aurora from "../assets/portraits/aurora-frontier.webp";
import gaspar from "../assets/portraits/gaspar-frontier.webp";
import celeste from "../assets/portraits/celeste-frontier.webp";
import severino from "../assets/portraits/severino-frontier.webp";
import amara from "../assets/portraits/amara-frontier.webp";

export const HERO_PORTRAITS = { joao, maria, indigo, labuta, rosa, elias, silas, ada, ruth, teo, valeria, tomas, luzia, benicio, ines, dynamite,jacinto,aurora,gaspar,celeste,severino,amara };
export const BENTO_PORTRAIT = bento;
