import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const audit=JSON.parse(fs.readFileSync('docs/supplied-assets-audit.json','utf8'));
const destination='src/assets/supplied';fs.mkdirSync(destination,{recursive:true});
const entries=audit.assets.map(asset=>{
  const bytes=fs.readFileSync(path.join(audit.source,asset.file));
  if(crypto.createHash('sha256').update(bytes).digest('hex')!==asset.sha256)throw new Error('Hash changed: '+asset.file);
  const id=asset.file.slice(0,-4).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');
  fs.copyFileSync(path.join(audit.source,asset.file),`${destination}/${id}.glb`);
  return {...asset,id,license:'User supplied; user confirms unrestricted game use on 2026-09-26. No independent license document supplied.',admission:'accepted by user',path:`${destination}/${id}.glb`};
});
if(new Set(entries.map(a=>a.id)).size!==entries.length)throw new Error('Duplicate ID');
fs.writeFileSync(`${destination}/manifest.json`,JSON.stringify({schema:1,authorization:'Explicit user confirmation in this conversation, 2026-09-26',assets:entries},null,2));
fs.writeFileSync('src/config/suppliedAssets.js',`// Generated by admitSuppliedAssets.mjs; original filenames and hashes in assets/supplied/manifest.json.\nexport const SUPPLIED_ASSETS = {\n${entries.map(a=>`${JSON.stringify(a.id)}:{url:new URL(${JSON.stringify('../assets/supplied/'+a.id+'.glb')},import.meta.url).href,stage:${JSON.stringify(a.destination)},role:${JSON.stringify(a.role)}},`).join('\n')}\n};\n`);
console.log(`Admitted ${entries.length} assets; originals preserved.`);
